[project]
name = "levi-cli"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kosong[contrib]>=0.33.0,<0.34.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "rich>=14.2.0",
    "typer>=0.21.0",
]
